export default function Loading() {
  return (
    <h1 style={{ color: "white" }}>
      dncekrlsbferjhfbjulerfhulkehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknfehfkudfkenfknf
    </h1>
  );
}
